#!/bin/sh
rm /var/tmp/gamelist
rm /var/tmp/game_desc_list
ls -l /usr/ports/games/*/pkg-descr | cut -w -f 9 >> /var/tmp/gamelist
for path in `cat /var/tmp/gamelist`
do
echo "---" >> /var/tmp/game_desc_list
echo $path | sed -e "s:Makefile::1" -e  "s:/usr/ports/games/::1" -e "s:/pkg-descr::1" |tee -a /var/tmp/game_desc_list
echo "">> /var/tmp/game_desc_list
cat  $path >> /var/tmp/game_desc_list
echo "">> /var/tmp/game_desc_list
echo "">> /var/tmp/game_desc_list
done
echo; echo "---"; echo "Task complete."
cat /var/tmp/gamelist |sed -e "s:Makefile::1" -e  "s:/usr/ports/::1" -e "s:/pkg-descr::1" > games_list
cp /var/tmp/game_desc_list games_descriptions
